server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mp?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: qqq3ww2e1
    driver-class-name: com.mysql.cj.jdbc.Driver
   
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  type-aliases-package: com.wu.entity 

 
logging:
  level:
    root: warn
    com.wu.mapper: trace
  pattern:
    console: '%p%m%n'
 